# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 14

# Number of days of inactivity before an Issue or Pull Request with the stale
# label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually,
# but will remain marked as stale.
daysUntilClose: 30

# Issues or Pull Requests with these labels will never be considered stale.
# Set to `[]` to disable
exemptLabels:
  - dependencies
  - draft
  - WIP

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This PR has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when removing the stale label.
# unmarkComment: >
#   Your comment here.

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This PR has been automatically closed because it has not had recent activity.
  You can reopen it by clicking on `Reopen pull request`.
  Thank you for your contributions.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Limit to only `issues` or `pulls`
only: issues
