# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

formatting:
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 2
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 2
  MaximumLineLength:
    maxLineLength: 160

performance:
  SpreadOperator:
    active: false

style:
  ClassOrdering:
    active: true
    autoCorrect: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  ForbiddenComment:
    active: true
    values: [ ]
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreRanges: true
    ignoreEnums: true
    excludes: [ '**/*Theme*' ]
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenVoid:
    active: true
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  MultilineLambdaItParameter:
    active: true
  ObjectLiteralToLambda:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantHigherOrderMapUsage:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseIsNullOrEmpty:
    active: true
  UseOrEmpty:
    active: true
  UseRequire:
    active: true
  UseRequireNotNull:
    active: true
  ReturnCount:
    max: 3

comments:
  AbsentOrWrongFileLicense:
    active: true
  DeprecatedBlockTag:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true

complexity:
  NamedArguments:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true
  TooManyFunctions:
    ignorePrivate: true
    ignoreOverridden: true

naming:
  NoNameShadowing:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true

potential-bugs:
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
  HasPlatformType:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  UnreachableCatchBlock:
    active: true
  UnusedUnaryOperator:
    active: true
