# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

exceptions:
  InstanceOfCheckForException:
    active: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
  NotImplementedDeclaration:
    active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
    ignoredExceptionTypes:
      - InterruptedException
      - MalformedURLException
      - NumberFormatException
      - ParseException
    allowedExceptionNameRegex: _|(ignore|expected).*

formatting:
  autoCorrect: true
  AnnotationOnSeparateLine:
    active: true
  AnnotationSpacing:
    active: true
  ArgumentListWrapping:
    active: true
    maxLineLength: 160
  Indentation:
    active: true
    indentSize: 2
    continuationIndentSize: 2
  MultiLineIfElse:
    active: true
  NoEmptyFirstLineInMethodBlock:
    active: true
  NoMultipleSpaces:
    active: false
  NoWildcardImports:
    excludes:
      - '**/*Steps*'
  PackageName:
    active: true
  ParameterListWrapping:
    active: true
    indentSize: 2
  SpacingBetweenDeclarationsWithAnnotations:
    active: true
  SpacingBetweenDeclarationsWithComments:
    active: true
  MaximumLineLength:
    maxLineLength: 160

performance:
  SpreadOperator:
    active: false

style:
  SerialVersionUIDInSerializableClass:
    active: false
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenVoid:
    active: true
  ForbiddenComment:
    active: true
    values: []
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreRanges: true
    ignoreEnums: true
    excludes:
      - '**/*Theme*'
      - '**/*Painter*'
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  MultilineLambdaItParameter:
    active: true
  NoTabs:
    active: true
  ObjectLiteralToLambda:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantHigherOrderMapUsage:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    max: 3
    excludeGuardClauses: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseAnyOrNoneInsteadOfFind:
    active: true
  UseArrayLiteralsInAnnotations:
    active: true
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIsNullOrEmpty:
    active: true
  UseOrEmpty:
    active: true
  UseRequire:
    active: true
  UseRequireNotNull:
    active: true

comments:
  AbsentOrWrongFileLicense:
    active: true
  DeprecatedBlockTag:
    active: true
  OutdatedDocumentation:
    active: true
    matchTypeParameters: true
    matchDeclarationsOrder: true
  UndocumentedPublicClass:
    active: false
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/*Bundle*'
      - '**/actions/**'
  UndocumentedPublicFunction:
    active: false
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/*Bundle*'
      - '**/actions/**'

complexity:
  LargeClass:
    active: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/*Resources*'
  NamedArguments:
    active: true
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true
    threshold: 3
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: $^
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/build.gradle.kts'
  TooManyFunctions:
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11
    ignoreDeprecated: false
    ignorePrivate: true
    ignoreOverridden: true

naming:
  InvalidPackageDeclaration:
    active: true
  LambdaParameterNaming:
    active: true
  NoNameShadowing:
    active: true
  NonBooleanPropertyPrefixedWithIs:
    active: true
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 36
    excludes:
      - '**/*Page*'
      - '**/*Settings*'
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 2
  VariableMaxLength:
    active: true


potential-bugs:
  AvoidReferentialEquality:
    active: true
  CastToNullableType:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
  HasPlatformType:
    active: true
  ImplicitUnitReturnType:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: true
    excludes:
      - '**/*.kts'
  MissingWhenCase:
    active: true
  NullableToStringCall:
    active: true
  UnreachableCatchBlock:
    active: true
  UnusedUnaryOperator:
    active: true
